drop table if exists meta;
create table if not exists meta(version integer);
insert into meta values(1);
create table IF NOT EXISTS todo(id integer,subject text,checked integer,pid integer);
create table IF NOT EXISTS project(id integer,name text);
insert into project values(1,'default1');
insert into project values(2,'project1');
insert into todo values(1,'todo 1',1,1);
insert into todo values(1,'todo 2',1,1);
insert into todo values(1,'todo 11',1,2);
insert into todo values(1,'todo 22',1,2);
drop table if exists milk;
create table milk (id integer,qty integer,d text,t text);
insert into milk values(1,120,'2023-09-10','09:00');